### ISSUE TITLE
"Uniform tiling" in scope

### ISSUE THREAD

**Issue by jw3126** [JuliaArrays/TiledIteration.jl#22]
I have an image and I want to decompose it into tiles. Such that
* All tiles have the same fixed size
* Tiles should overlap as little as possible and as uniformly as possible. E.g.
```julia
img = 1:9
size = 4
tiles(img, size) = [1:4, 5:8, 6:9] # bad last tile has huge overlap
tiles(img, size) = [1:4, 4:7, 6:9] # good
tiles(img, size) = [1:4, 3:6, 6:9] # also good
```
Is that in scope of this package? Suggestions for another package, where this could live?

**Comment by johnnychen94** [comment]
As long as it makes sense, this package could support overlapping tiles and other more delicate iteration strategies.

I'm not sure what makes one iteration good and the other bad. `[1:4, 5:8, 6:9]` has three points overlapped and `[1:4, 4:7, 6:9]` also has three points overlapped, why should we reject the first possibility? More importantly, This package should only handle how image grids are broken into tiles, not compositing tiles into image grids. There are completely two different tasks.

**Comment by jw3126** [comment]
In my context, I want the overlap sizes to be all of roughly the same size. That is what I called uniform. In the first example, the overlap sizes are `0, 3`. In the other examples it is `1,2` or `2,1` which is more balanced. 
Maybe a better more extreme example would be 
```julia
tiles(1:101, 50) = [1:50, 51:100, 52:100] # bad the last two tiles are nearly the same
tiles(1:101, 50) = [1:50, 26:75, 52:100] # good rougly 25 elements of overlap everywhere
```
Yes image and grid decomposition are orthogonal and I am happy to have only the grid decomposition here.

**Comment by johnnychen94** [comment]
Hmmm, let me reword a bit. IMO both `tiles(1:101, 50) == [1:50, 51:100, 52:100]` and `tiles(1:101, 50) == [1:50, 26:75, 52:100]` are decomposition strategies and I think both are valid candidate to be added into this repo.

We might just figure out how to extend the current semantics without breaking changes.

**Comment by jw3126** [comment]
I did not mean that one or the other strategy is superiour in general. It's just that what I need at the moment is a balanced/uniform strategy.
